export const TAG_SYNONYMS: Record<string, string> = {
    child: "kids",
    children: "kids",
    kid: "kids",
    family: "family",
    adult: "adults",
    adults: "adults",
    silent: "low-noise",
    quiet: "low-noise",
    lownoise: "low-noise",
    mediumnoise: "medium-noise",
    loud: "high-noise",
    sound: "high-noise",
    eco: "eco-friendly",
    green: "eco-friendly",
    safe: "safe",
    affordable: "budget",
    cheap: "budget",
    luxury: "premium",
    premium: "premium",
    colourful: "colorful",
    colorful: "colorful",
    apartment: "apartment-friendly",
};