export const PRODUCT_IMPORT_SCHEMA_V1 = {
    name: { required: true, type: "string", minLength: 3 },
    description: { required: false, type: "string" },
    price: { required: true, type: "number", min: 1 },
    quantity: {
        required: true,
        type: "number",
        min: 0,
        default: 0,
    },
    brandId: { required: true, type: "string" },
    categoryId: { required: true, type: "string" },
    videoUrl: { required: false, type: "string" },
    isActive: { required: false, type: "boolean", default: true },
    packageTagIds: { required: false, type: "string" },
    aiTags: { required: false, type: "string" },
    discountMode: { required: false, type: "string" },
    discountValue: { required: false, type: "number" },
    discountPriority: {
        required: false,
        type: "number",
        default: 1,
    },
    discountActive: {
        required: false,
        type: "boolean",
        default: true,
    },
    IsComboPackage: {
        required: false,
        type: "boolean",
        default: false,
    },
    sequenceNumber: {
        required: true,
        type: "number",
        default: 0,
    },
    productFamily: {
        required: true,
        type: "string",
        default: "",
    },
    isBulkOnly: { required: false, type: "boolean", default: false, },
    cartonQty: { required: false, type: "number", min: 0 },
    scheme1Price: { required: false, type: "number", min: 0 },
    scheme2Price: { required: false, type: "number", min: 0 },
    scheme3Price: { required: false, type: "number", min: 0 },
    scheme4Price: { required: false, type: "number", min: 0 },

} as const;